### ISSUE TITLE
Observed periodic "Cannot set header" warnings in Open Liberty

### ISSUE THREAD

**Issue by jesse-gallagher** [jesse-gallagher/frostillic.us-Blog#25]
There are a couple sources of it, but the stack traces all look similar to:

```
[WARNING ] SRVE8094W: WARNING: Cannot set header. Response already committed.  Stack trace of errant attempt to set header: 
        at com.ibm.ws.webcontainer.srt.SRTServletResponse.setHeader(SRTServletResponse.java:1759)
        at [internal classes].(Unknown Source)
        at com.darwino.j2ee.servlet.server.servlet.ServiceDispatcherFilter.doFilter(ServiceDispatcherFilter.java:179)
        at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
        at [internal classes].(Unknown Source)
        at com.darwino.j2ee.servlet.resources.GlobalPathRewriterFilter.doFilter(GlobalPathRewriterFilter.java:91)
        at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
        at [internal classes].(Unknown Source)
        at com.darwino.j2ee.application.DarwinoJ2EEFilter.doFilter(DarwinoJ2EEFilter.java:221)
        at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
        at [internal classes].(Unknown Source)
        at com.darwino.j2ee.servlet.authentication.AuthenticationFilter.chainFilter(AuthenticationFilter.java:219)
        at com.darwino.j2ee.servlet.authentication.AuthenticationFilter.doFilter(AuthenticationFilter.java:211)
        at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
        at [internal classes].(Unknown Source)
```

It's just a warning, and there's no apparent user-side trouble, but it'd be nice to track down what's doing it.

**Comment by jesse-gallagher** [comment]
Failing that, it'd be useful to find out if there's a way to suppress the warning by code for Liberty, and include that in the README.
