### ISSUE TITLE
Observed IllegalArgumentException to do with headers on Liberty 20.0.0.4

### ISSUE THREAD

**Issue by jesse-gallagher** [jesse-gallagher/frostillic.us-Blog#81]
```
[err] Service Error 500, Invalid LF not followed by whitespace
[err] {
  "status": 500,
  "message": "Invalid LF not followed by whitespace",
  "time": "2020-05-05T10:25:01.929-04:00"
}
[err] java.lang.IllegalArgumentException: Invalid LF not followed by whitespace
[err] 	at com.ibm.ws.genericbnf.internal.BNFHeadersImpl.checkHeaderCharacters(BNFHeadersImpl.java:2933)
[err] 	at [internal classes]
[err] 	at com.darwino.j2ee.servlet.server.http.ServletServiceContext.setResponseHeader(ServletServiceContext.java:376)
[err] 	at com.darwino.commons.services.AbstractHttpServiceContext.emitException(AbstractHttpServiceContext.java:627)
[err] 	at com.darwino.j2ee.servlet.server.servlet.ServiceDispatcherFilter.doFilter(ServiceDispatcherFilter.java:169)
[err] 	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
[err] 	at [internal classes]
[err] 	at com.darwino.j2ee.servlet.resources.GlobalPathRewriterFilter.doFilter(GlobalPathRewriterFilter.java:91)
[err] 	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
[err] 	at [internal classes]
[err] 	at com.darwino.j2ee.application.DarwinoJ2EEFilter.doFilter(DarwinoJ2EEFilter.java:221)
[err] 	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
[err] 	at [internal classes]
[err] 	at com.darwino.j2ee.servlet.authentication.AuthenticationFilter.chainFilter(AuthenticationFilter.java:223)
[err] 	at com.darwino.j2ee.servlet.authentication.AuthenticationFilter.doFilter(AuthenticationFilter.java:211)
[err] 	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
[err] 	at [internal classes]
[err] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[err] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[err] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jesse-gallagher** [comment]
This is related to the remote LDAP server being down. It's setting `X-Darwino-Error` with the value `Service Error 500, Error while creating the JNDI context\njavax.naming.CommunicationException: terminus-dwo.galaxia:389 [Root exception is java.net.ConnectException: Connection refused (Connection refused)]`

**Comment by jesse-gallagher** [comment]
Fixed upstream in Darwino
